// Generated by CoffeeScript 1.4.0
(function() {

  window.LineSegment = (function() {

    function LineSegment(a, b) {
      var xe, _ref;
      this.a = a;
      this.b = b;
      if (this.a.x > this.b.x) {
        _ref = [this.b, this.a], this.a = _ref[0], this.b = _ref[1];
      }
      this.slope = (this.b.y - this.a.y) / (this.b.x - this.a.x);
      this.yIntercept = this.a.y - (this.a.x * this.slope);
      if (this.a.x > this.b.x) {
        alert("BIG TROUBLE:  a:" + this.a.x + " b:" + this.b.x);
      }
      xe = this.a.x + .0001;
      this.plusEpsilon = {
        x: xe,
        y: this.pointAt(xe)
      };
    }

    LineSegment.prototype.comparePoint = function(pt) {
      var onLine;
      onLine = this.pointAt(pt.x);
      switch (false) {
        case pt.y !== onLine:
          return 0;
        case !(pt.y > onLine):
          return -1;
        case !(pt.y < onLine):
          return 1;
      }
    };

    LineSegment.prototype.pointAt = function(x) {
      return x * this.slope + this.yIntercept;
    };

    LineSegment.prototype.toString = function() {
      return "(" + this.a.x + ", " + this.a.y + ") -> (" + this.b.x + ", " + this.b.y + ")";
    };

    return LineSegment;

  })();

}).call(this);
