// Generated by CoffeeScript 1.4.0
(function() {
  var height, svg;

  height = 400;

  svg = d3.select("body").append("svg").attr("width", 700).attr("height", height).attr("class", editModeClass);

}).call(this);
